remove configure hook
as it fails with error

error: cannot perform the following tasks:
- Run configure hook of "checkbox-kivu-classic24" snap if present (run hook "configure":
-----
python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by python3)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by python3)
-----)